# Gradle
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

jobs:
#  - job: Linux
#    pool:
#      vmImage: 'Ubuntu-16.04'
#    steps:
#      - template: gradle-steps.yml

#  - job: Mac_OS
#    pool:
#      vmImage: 'macOS-10.13'
#    steps:
#      - template: gradle-steps.yml

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: filePath
          filePath: azure-jdk-install.ps1
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '1.11'
          jdkArchitectureOption: x64
          jdkSourceOption: localDirectory
          jdkFile: $(Agent.BuildDirectory)\openjdk-11.0.1_windows-x64_bin.zip 
#          jdkDestinationDirectory: $env:JAVA_HOME_11_X86
      - template: gradle-steps.yml
