trigger:
  - master

jobs:
  # Linux job
  - template: build-job.yml
    parameters:
      name: Linux
      platform: linux
      pool:
        vmImage: 'ubuntu-16.04'
      jpkgjdk: 'jdk14jpackagelinux'
      jpkgdir: 'jdk-14'

  # Mac OS job
  - template: build-job.yml
    parameters:
      name: MacOS
      platform: mac
      pool:
        vmImage: 'macOS-10.13'
      jpkgjdk: 'jdk14jpackagemac'
      jpkgdir: 'jdk-14.jdk'

  # Windows job
  - template: build-job.yml
    parameters:
      name: Windows
      platform: win
      pool:
        vmImage: 'windows-2019'
      jpkgjdk: 'jdk14jpackagewindows'
      jpkgdir: 'jdk-14'
