# Gradle
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      platform: linux
    steps:
      - template: gradle-steps.yml

  - job: Mac_OS
    pool:
      vmImage: 'macOS-10.13'
    variables:
      platform: mac
    steps:
      - template: gradle-steps.yml

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      platform: win
    steps:
        # TODO: consider using Chocolatey to install OpenJDK
        #  - Package: https://chocolatey.org/packages/openjdk
        #  - VSTS Task: https://marketplace.visualstudio.com/items?itemName=jungeriusit.jungit-choco
      - task: PowerShell@2
        inputs:
          targetType: filePath
          filePath: azure-jdk-install.ps1
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '1.11'
          jdkArchitectureOption: x64
          jdkSourceOption: localDirectory
          jdkFile: $(Agent.ToolsDirectory)\openjdk-11.0.1_windows-x64_bin.zip
          jdkDestinationDirectory: $(Agent.ToolsDirectory)\Java11
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew.bat'
          jdkVersionOption: 'default'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          tasks: 'jlinkZip'
      - template: publish-steps.yml
