# Gradle
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - template: gradle-steps.yml

  - job: Mac OS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: gradle-steps.yml
