# Gradle
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      platform: linux
    steps:
      - template: gradle-steps.yml

  - job: Mac_OS
    pool:
      vmImage: 'macOS-10.13'
    variables:
      platform: mac
    steps:
      - template: gradle-steps.yml

  - job: Windows
    pool:
      vmImage: 'windows-2019'
    variables:
      platform: win
    steps:
      - template: gradle-steps.yml
