parameters:
  name: ''
  pool: ''
  platform: ''
  sign: false
  jpkgjdk: ''
  jpkgdir: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
    - task: DownloadPackage@1
      inputs:
        packageType: 'upack'
        feed: brunocborges
        definition: ${{ parameters.jpkgjdk }}
        version: '0.0.1'
        extract: false
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(System.DefaultWorkingDirectory)/openjdk**'
        destinationFolder: '$(System.DefaultWorkingDirectory)'
        cleanDestinationFolder: false
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'dist jpackage'
        gradleOptions: '-Dbadass.jlink.jpackage.home=$(System.DefaultWorkingDirectory)/${{ parameters.jpkgdir }}'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/build/distributions/'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/build/installer/'
